version: 1

default:
  SECRET_KEY: "change-me-in-production"
  JWT_SECRET_KEY: "jwt-secret-change-in-production"
  JWT_ACCESS_TOKEN_EXPIRES: 1800  # 30 minutes in seconds
  CORS_ORIGINS: "*"
  MAX_CONTENT_LENGTH: 16777216  # 16MB
  DOCS_URL: "/docs"
  REDOC_URL: "/redoc"
  OPENAPI_URL: "/openapi.json"
  OPENAPI_PREFIX: ""

  # OPA policy enforcement (Open Policy Agent)
  ENABLE_OPA_POLICIES: true          # Feature flag to enable/disable OPA checks
  OPA_HOST: "http://localhost"       # OPA server base URL
  OPA_PORT: 8181                      # OPA server port
  OPA_POLICY_PATH: "agentictrust/authz/allow"   # Data path to the allow rule

environments:
  development:
    DEBUG: true
    HOST: "127.0.0.1"
    PORT: 8000
    RELOAD: true
    CORS_ORIGINS: ["http://localhost:3000", "http://127.0.0.1:3000"]
    DATABASE_URL: "sqlite:///agentictrust.db"
    LOG_LEVEL: "debug"
    
  testing:
    DEBUG: false
    HOST: "127.0.0.1"
    PORT: 8000
    RELOAD: false
    DATABASE_URL: "sqlite:///instance/test.db"
    LOG_LEVEL: "info"
    
  production:
    DEBUG: false
    HOST: "0.0.0.0"
    PORT: 8000
    RELOAD: false
    CORS_ORIGINS: []  # Set specific allowed origins in production
    DATABASE_URL: "sqlite:///instance/prod.db"  # Change to production database
    LOG_LEVEL: "warning"
    DOCS_URL: null  # Disable Swagger UI in production
    REDOC_URL: null  # Disable ReDoc in production

# OAuth settings
oauth:
  TOKEN_EXPIRATION_SECONDS: 3600
  REFRESH_TOKEN_EXPIRATION_SECONDS: 86400
  SCOPE_EXPANSION_POLICY: "standard"
  ACCESS_TOKEN_FORMAT: "jwt"
  ENABLE_REFRESH_TOKENS: true
  JWT_ALGORITHM: "HS256"
