# OAuth Scopes Configuration
# This file defines all available OAuth scopes for the AgenticTrust platform

scopes:
  # Read Permissions
  - name: profile:read
    description: Read basic profile information about the agent
    category: read
    is_default: true
    is_sensitive: false

  - name: read:web
    description: Allow reading web content for information gathering
    category: read
    is_default: true
    is_sensitive: false

  - name: tools:read
    description: View available tools and their descriptions
    category: read
    is_default: false
    is_sensitive: false
  
  # Write Permissions
  - name: content:write
    description: Create or modify content on behalf of the user
    category: write
    is_default: false
    is_sensitive: false
  
  - name: data:write
    description: Store data in the application database
    category: write
    is_default: false
    is_sensitive: false
  
  # Admin Permissions
  - name: admin
    description: Full administrative access (use with caution)
    category: admin
    is_default: false
    is_sensitive: true
  
  - name: delete:*
    description: Delete resources across the system
    category: admin
    is_default: false
    is_sensitive: true
  
  # Tool Permissions
  - name: tools:use
    description: Use registered tools within the platform
    category: tool
    is_default: false
    is_sensitive: false
  
  - name: tools:register
    description: Register new tools in the system
    category: tool
    is_default: false
    is_sensitive: false
    requires_approval: true
